import Head from "next/head";
import Image from "next/image";
import styles from "../styles/Home.module.css";
import Link from "next/link";

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Codesolver</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      {/* <Script src='test.js' strategy="lazyOnload" >

      </Script> */}

      <main className={styles.main}>
        <h1 className={styles.title}>code Solver</h1>

        <p className={styles.description}>
          This is a blog for a millions of code solver
        </p>
        <div className={styles.content}>
          <Link href="/blogpost">
            <h1 className={styles.contenth1}>
              Do you want to learn how the problems are solved in javascript?
            </h1>
          </Link>
          <h4>See other people how they tackel the problem</h4>
        </div>
      </main>

      <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{" "}
          <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer>
    </div>
  );
}
